
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    Col0 = @"Этого черепашонка зовут Краш а мистер Черепашка - его отец.",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");


Console.WriteLine($"Col0: {@"Этого черепашонка зовут Краш а мистер Черепашка - его отец."}");
Console.WriteLine($"Col1: {2F}");


Console.WriteLine($"\n\nPredicted Col1: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

